In [1]:
import yfinance as yf
import pandas as pd
import numpy as np

In [2]:
link = 'https://en.wikipedia.org/wiki/NIFTY_50'

symbols = pd.read_html(link)[2]['Symbol']

symbols = symbols + ".NS"

symbols = symbols.to_list()

In [3]:
start = '2010-01-01'

prices = yf.download(symbols, start = start)['Close']

prices

[*********************100%***********************]  50 of 50 completed

,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-04,69.219017,111.349998,347.149994,178.865005,198.419998,866.025024,35.314632,33.334953,298.591614,108.458336,...,150.735001,94.925003,163.535919,60.379684,375.825012,255.750000,71.074997,966.099976,116.233330,156.105011
2010-01-05,70.820740,115.190002,366.375000,179.429993,202.559998,870.025024,35.393230,33.111488,303.320221,106.824997,...,155.264999,102.285004,160.686478,61.842136,375.924988,259.024994,72.532501,986.099976,121.933334,158.568756
2010-01-06,77.810081,120.900002,353.924988,178.889999,199.160004,856.575012,34.558136,33.587563,300.106598,105.216667,...,157.279999,103.885002,160.933823,61.170456,367.424988,260.299988,73.699997,987.299988,119.766663,155.362503
2010-01-07,74.598969,119.470001,356.924988,177.065002,200.570007,841.549988,34.287960,33.383530,302.447968,103.175003,...,154.884995,104.250000,155.432831,61.908825,357.200012,254.574997,75.532501,978.349976,118.633331,152.606262
2010-01-08,75.541611,119.330002,355.725006,179.990005,203.190002,827.625000,34.386208,33.990768,298.453888,104.925003,...,157.494995,104.769997,156.283707,61.780209,349.899994,261.274994,74.834999,990.299988,117.900002,150.311264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-07-14,2376.100098,726.099976,5171.799805,3429.750000,957.049988,4859.600098,1614.199951,7482.350098,886.500000,379.549988,...,1072.949951,851.500000,624.900024,117.150002,3514.649902,1228.650024,3055.550049,8182.549805,639.549988,405.049988
2023-07-17,2408.550049,731.049988,5219.299805,3460.399902,964.849976,4833.149902,1610.250000,7510.950195,878.099976,381.750000,...,1077.599976,852.599976,618.500000,117.750000,3491.699951,1242.400024,3033.449951,8251.000000,643.799988,415.250000
2023-07-18,2416.899902,728.150024,5162.600098,3513.449951,963.650024,4860.600098,1618.300049,7420.000000,875.450012,378.950012,...,1067.150024,858.700012,612.099976,116.599998,3496.850098,1247.550049,2996.449951,8176.000000,639.950012,417.200012
2023-07-19,2423.750000,731.400024,5175.600098,3514.649902,964.299988,4823.649902,1644.099976,7584.700195,870.750000,384.549988,...,1081.849976,860.450012,620.599976,116.699997,3470.050049,1244.699951,2995.649902,8329.200195,639.150024,417.950012
2023-07-20,2426.750000,732.799988,5192.350098,3524.699951,978.000000,4863.649902,1633.650024,7572.000000,882.000000,NaN,...,1099.699951,869.750000,621.700012,116.949997,3470.000000,1248.000000,2979.250000,8210.849609,639.250000,416.750000

In [4]:
percent_change = prices.pct_change()

# Taking product of the daily fractional change over a month to get the fractional change in stock price over a month
monthly_return = (percent_change + 1).resample('M').prod()

In [5]:
monthly_return

,ADANIENT.NS,ADANIPORTS.NS,APOLLOHOSP.NS,ASIANPAINT.NS,AXISBANK.NS,BAJAJ-AUTO.NS,BAJAJFINSV.NS,BAJFINANCE.NS,BHARTIARTL.NS,BPCL.NS,...,SUNPHARMA.NS,TATACONSUM.NS,TATAMOTORS.NS,TATASTEEL.NS,TCS.NS,TECHM.NS,TITAN.NS,ULTRACEMCO.NS,UPL.NS,WIPRO.NS
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-31,0.981510,1.069062,0.982212,1.035530,1.033868,1.009035,0.886354,0.899155,0.942189,0.831118,...,0.977245,0.964077,0.840160,0.897988,0.979445,0.950635,1.055857,0.962633,0.891311,0.933915
2010-02-28,1.097800,1.132140,1.001540,0.977189,1.096324,1.040024,1.089454,0.973582,0.911717,1.042711,...,1.045246,1.024477,1.024267,1.009225,1.034773,0.916041,1.163469,1.118333,0.974260,1.045605
2010-03-31,0.965269,1.171774,1.068155,1.126468,1.038906,1.108464,0.968453,1.066589,1.118847,0.918610,...,1.163863,1.044051,1.065382,1.100461,1.024744,0.957625,1.054030,1.110379,0.985469,1.043469
2010-04-30,1.197679,0.935917,1.075183,1.019594,1.087096,1.038987,1.023204,1.338536,0.955207,0.998938,...,0.876786,1.075803,1.151643,0.979116,0.980465,0.907514,1.156824,0.842317,1.140751,0.949855
2010-05-31,0.964803,0.942422,0.946328,1.003512,0.970354,1.055414,1.282163,1.064366,0.880590,1.122995,...,1.059159,1.029296,0.865230,0.809081,0.970800,0.821751,1.043560,0.947571,1.070212,0.997245
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-03-31,1.283462,1.066588,0.979383,0.976262,1.017060,1.061059,0.948760,0.918956,1.009094,1.084922,...,1.027702,0.990983,1.000238,1.005291,0.967717,1.001454,1.059887,1.049695,1.033780,0.943677
2023-04-30,1.099689,1.078177,1.047044,1.050948,1.001747,1.140859,1.069601,1.118102,1.067156,1.038629,...,1.004628,1.077590,1.152448,1.033014,1.004164,0.929074,1.050479,0.991348,1.031561,1.054073
2023-05-31,1.295280,1.084471,1.023983,1.100126,1.063779,1.030506,1.071162,1.113016,1.063305,1.016499,...,0.987546,1.045559,1.085266,0.980083,1.021822,1.089724,1.068664,1.041535,0.925436,1.048442
2023-06-30,0.957768,1.000541,1.103041,1.052960,1.079357,1.027238,1.053031,1.024428,1.033945,1.003301,...,1.078177,1.077944,1.131579,1.058601,1.003876,1.013715,1.079483,1.053964,1.003576,0.964078
2023-07-31,1.016206,0.991275,1.018467,1.048378,0.990430,1.036683,1.069143,1.057453,1.003698,1.054428,...,1.045740,1.010280,1.043909,1.044196,1.050799,1.103595,0.977557,0.989885,0.929751,1.070924

In [9]:
def WinnerStocks(date, lookback, holding, no_stocks):
    try:
        # Define the monthly returns in stocks over the lookback period
        monthly_return_lb = monthly_return.rolling(lookback - 1).apply(np.prod).dropna()

        # Pick the largest n stocks from the lookback period given a date
        winners = monthly_return_lb.loc[date - pd.offsets.MonthEnd(1)].nlargest(no_stocks)

        # Pick these stocks to invest in at the current date
        current_ret = monthly_return[winners.name:][1 : 1 + holding][winners.index].rolling(holding).apply(np.prod)

        # Return the average returns over the perios for all the stocks
        if not current_ret.empty:
            return (current_ret).mean(axis = 1).values[0]
    except:
        return 1

In [10]:
def Portfolio_Returns(lookback, holding, no_stocks):
    port_returns = []

    # Define the monthly returns in stocks over the lookback period
    monthly_return_lb = monthly_return.rolling(lookback - 1).apply(np.prod).dropna()

    # Calculate the returns over the entire monthly return dataset
    for date in monthly_return_lb.index[:114:holding]:
        port_returns.append(WinnerStocks(date, lookback, holding, no_stocks))

    # Return the net returns of the investment scheme
    return round(pd.Series(port_returns).prod(), 10)

In [28]:
Portfolio_Returns(3, 1, 5)

4.5167176957

In [11]:
# Compilation of Results from different Momentum Strategies

returns = []
for n in [5, 10, 15, 20]:
    returns_for_given_n = []
    for J in [3,6,9,12]:
        returns_for_given_n_row = []
        
        for K in [3,6,9,12]:
            returns_for_given_n_row.append(Portfolio_Returns(J,K,n))
            
        returns_for_given_n.append(returns_for_given_n_row)
        
    returns.append(returns_for_given_n) 

print(returns)

[[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]]

In [33]:
#n=5

df5 = {'J = 3':returns[0][0],
      'J = 6':returns[0][1],
      'J = 9':returns[0][2],
      'J = 12':returns[0][3]}

df5 = pd.DataFrame(df5,index = ['K = 3','K = 6','K = 9','K = 12'])

print(df5)

           J = 3     J = 6     J = 9    J = 12
K = 3   0.941426  1.171014  0.971513  1.118850
K = 6   0.819056  0.953396  0.920664  1.005920
K = 9   0.945013  1.130270  1.242473  1.214603
K = 12  0.928310  1.152477  1.192950  1.202664

In [28]:
#n=10
df10 = {'J = 3':returns[1][0],
      'J = 6':returns[1][1],
      'J = 12':returns[1][2]}

df10 = pd.DataFrame(df10,index = ['K = 1','K = 3','K = 6','K = 12'])

print(df10)

        J = 3  J = 6  J = 12
K = 1    5.20   5.62    5.02
K = 3    4.82   5.58    7.02
K = 6    3.24   4.07    5.79
K = 12   3.99   5.05    9.75

In [29]:
#n=15
df15 = {'J = 3':returns[2][0],
      'J = 6':returns[2][1],
      'J = 12':returns[2][2]}

df15 = pd.DataFrame(df15,index = ['K = 1','K = 3','K = 6','K = 12'])

print(df15)

        J = 3  J = 6  J = 12
K = 1    4.40   5.30    5.09
K = 3    3.76   5.50    6.59
K = 6    3.12   4.43    5.66
K = 12   4.28   4.55    7.57

In [ ]:
#n=20
df20 = {'J = 3':returns[3][0],
      'J = 6':returns[3][1],
      'J = 12':returns[3][2]}

df20 = pd.DataFrame(df20,index = ['K = 1','K = 3','K = 6','K = 12'])

print(df20)